apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt
  namespace: pangolin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt
  template:
    metadata:
      labels:
        app: newt
    spec:
      containers:
        - name: newt
          image: fosrl/newt
          envFrom:
            - secretRef:
                name: newt-secret
