apiVersion: v1
kind: Secret
metadata:
  name: newt-secret
  namespace: pangolin
type: Opaque
data:
  PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:o/UBkq5bKnCqnXf4U/dqvbdbrF6XvTGhVsh3So/ex1F8jHpq,iv:marUJjIO2xHo4eznWPmdbkC8ko/xgeGtwmOitNy6Mpc=,tag:k/B/4BeX6zgNt2LQiqF6WA==,type:str]
  NEWT_ID: ENC[AES256_GCM,data:jRlWGTem0/VPJ6jtZ0YZgIq55tg=,iv:wroLWI8xuuRm5t4NYUirOtRFvYH4WxSjbs27y09fPGU=,tag:QST0cvOos64dyc3VUCbM3Q==,type:str]
  NEWT_SECRET: ENC[AES256_GCM,data:SKfn6vDRFcmIFGPqOnLkgEo+AxaRBHkF7pvmDkLP7uaoPgbJ7F1GSbL3tmP8ffwe+7B4lNTwYmmbZ+mR8HH8bA==,iv:rab6gmblnp5fX/e1PEoRFy4vrNUJWFFXa07BDohSDzs=,tag:EyjKf1qT5JeLBiCs8qWZ4g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UUZxdEY1SG03VTBDK1U0
        VEt3YmlNZGM1QVpEZWk3ekVVRWMvc0YxNlVRCjdpMlk4aTErM0gvbGoxYnd5M1VZ
        K2R0dEpUTnpoZzJyWG1ybWlDY2ZTQk0KLS0tIGxTTFBsc2pzcDB5NHN0ZitkNWhl
        aWR1VFhBVC9JSWZUN2xDbDlTMnU2YUkKU+3GDlXHrwDSkUcMj/Lm7P9MNdnrh98x
        /gHxF5Otp4JJSY2d6DtsjXaQWa6IBeqHEchYwhoPYzrzm1NGer3w1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T05:09:44Z"
  mac: ENC[AES256_GCM,data:EQJQntVKjmYY+rDj3g+25N7LAUbdQc11CoBQ8gwPLpZGnEUTQBrfZzHqVEGqYs0fV/mu4iis1D9uJfU+KYEB+5XJB2jHkEnJdglXOTWw0CpPZK5ydauXiY8GGFaQpQ0jzMNkG1T0+gQkz/NLDhHPh/uPeIQf7+mBCjh23mY7ylM=,iv:F2XXZPvOIRS25PlBmbAgHERKgPSNg+Nrnje/4ByKeaY=,tag:IADMj2yny5WZeP7oXRx6xg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|annotations|values|)$
  version: 3.8.1
