apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflared
type: Opaque
data:
    token: ENC[AES256_GCM,data:bLTb0Qd8WkFMeuVUUROWiu06xdg+GmvxYSsKQC0xfq1rLBRFFWGA9fDa5fpqo9HUIynio2YpcMxHJR0h8sUv2oNxMVEKDs0suoOzNbrif0bwwcXFqrfnKK2pUKv1cV25wbE+1qxrEO6Vs30oy4z+Pj9xpGRNSn39IwJcoPbuvOy+1QHk+RzTtyW8iMC5EMehSUwGaca2uFjK+g09JX4lYME0u+BuzG+Ral9e2k4gNQ4ccOJ+dJoRQyrdNDVsOUMJxSMZRH+YpCGo/QDvaCf6L+cAYYENJKJ2mKbQM0cT036Cnnadyg8ywI2QxpVgVUNKOq5WjiOWd3k=,iv:LRg5PPBgSpoems0mO7UEG82WcQywnTpTXdElEwR9e6c=,tag:VRgwfl0wySJOL7oNgYNLFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN1o0TzA1d2NYRktWSUow
            Rnp2aFBvREhtOXhSdWJlbkFKazBnV3Z5dm1NCjJqcmZpL1V1Yi9zUDVtQWpjNFcz
            TU5wMEx0MGRVWU9qWVR1WHBEZ1pnbUUKLS0tIFFSbTlyVVEycW8xZk12WE9oV0J1
            NFBCY0RtYWdpS0lvdlRIVkkwUjF5cDAKBvDhzIyMTHBnrVpCR4Cfaz+kWyxVRsLq
            ymOJms9ca75PE75rbij+0FnnO9pvcTT/bK23ys+2w33LF3oXZzZLaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T01:58:10Z"
    mac: ENC[AES256_GCM,data:ZUnP/NbF7DqP43AqHjFVgeGwbUnlJWTYPxlPMPM862CVnZ1gZ1+hM8HkIcAYRykA9VIPlg6fKNDGSP/vjD/EPcRNNG6f6VhP325c/aLkZgYHUCrQP19hTCGm3/v/N0jOupX1yG8v+bUJapHpKApxaKqEe8WEyxOxpzm44o0A+c8=,iv:v48IGJ1zKO6dFQqoaWKvBnBF5E/yRhealLLRAg35bIA=,tag:4lgTNcfHunxRaOz3E4yiTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
