apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflared
type: Opaque
data:
    tunnel-token: ENC[AES256_GCM,data:kMret3m+9rTuFnxUgR7TAZ8aPlhRhET3sirGJ/cE4MLYyHS3czLTHbkU9RLNhupGqUOgpCaFSoR8t8oo//Q8jyY6xQhxxjmS8CpNdRSEzmFgTt+ZQfwag4iZQZ25NXJmas2jrDoaqrJccqBV9gVRsZFKBfErY254qpYdKLUVj7Ru0xm1zVtaqRA2RTCbQv9FZtPcOp3aSs0ksW5wur+DC2nTbs88EV1t6ImoT+kmVkZZr47bezxmDzim5yVytg9iSWlVwBEh2VfbrXG4nNC+F5fNIdPlf156rOTzV/WQZYmv0c+EZve2ZkJjmE2T/uZpqQeuR36OMB4=,iv:HjI3oko6ch0qo2DwdHpdESwM375JF0oLtGFI8yiKBJI=,tag:ia+zWJIvX+I7rSf6jQMY1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldFRWMEp6U0NqYzFCc21u
            VU81SXpMMXRpSmR5YVdqelJoRnA0Nmw2SFRZCmovQXBDUGxRaUIxODFRRFBxM3ZI
            NHR2dkw5eHRHT24ybmtVSkZjNmZYbXMKLS0tIGxhd0hqenlqZlhyTUVVNVFZbDI2
            WC92WlhxUStUYm5qWWVHSG5aOWRUMlUKyFzte5yki8kTHiSi9yWsFd40rRBq4D81
            PhBUSO8+SqkFmaznJScFowWE6OAKZ8rWZdjhSYsBCRWWVz3LCMbAAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T01:55:48Z"
    mac: ENC[AES256_GCM,data:5HXK+G/kpBe0dzRaHgtxTm71hS7xkl0buyobL/R3jsv/pTCKOal4PIzSne7hICBWCaPYaLFkoFc2w1Y/qcK8HCW4ZGgoXhFoyh2MYMrsYJoJlpcs2NqxQaOUWPJ+VG+5sglchZOmJWYvgV20Ou0Y/EDEFczVv9WY//TkOneCdiQ=,iv:j6//kZPWPldZtJp21f/en8brni3UoXUUKYgTBIyjOpM=,tag:WIgkVresEpXt8jFbuqZvPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
