apiVersion: v1
kind: Secret
metadata:
  name: elastic-agent-enrollment-token
  namespace: kube-system
type: Opaque
data:
  enrollment-token: ENC[AES256_GCM,data:5WTnZtTPZ+uPoSTxI9Ubm+NWCaw9k1UzOrb6w4qaZMtt0IeJIK3n3af6DA3nTbNpdQp3EQrFKqfTqBuo4QrqZsGUciH8pNRvTcjIpoFk/6w=,iv:Ll7GXSe2Rf5yuXqm7067fMaOPpVblp97aAYQaHda5LA=,tag:2/FNt4Oapj75ursTL4BBtQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMUNlTjh5NEwvUUdTRVIz
        d2ZHa2FDMGU3U3UvODdvQUxXTytnaGtvV1JnCjhScXJjNEpYRXorNzQ5WVB3S0w0
        blZuYkQ1Yk9CdnIxVy9ITmtiamhOZEUKLS0tIGFUQTI0WVRONXJHejhzYVNFdjBp
        a1ZkZVhKaGd5cm11NkIvN3IxcEovWUEKZvgTm1V1QkjIB1g7v9mNtkOBFBwWm7ZX
        4SdaQdyPDiCa1lO7lcGVRtA7lrTId2Fwi78O+iikhvLYq/KxG2aWTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T16:04:17Z"
  mac: ENC[AES256_GCM,data:PMyGQhIs8G4A3oAFySzfqa1Y6W3DJ5XZA51Ud9IahqTKm/mtuT+yixTyOnhDrsmmnLq6zL51jBZkNYU9aSbH3IphK+P7wKIH0+KP6HvauSWnK8Domw2nLmURXoJBNTDIW7P5lM7bHhdeJYiw5Tb9Vwl9rwlqbrdSNwUvX0cZyXs=,iv:Phb1s6OrGEbzqDB2xGmVGa24dDc7thP2hXOpdId5UOQ=,tag:jx96rYATuo9QqR3Za2zOjg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|annotations|values|)$
  version: 3.8.1
