apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local-ip-list
  namespace: traefik
spec:
  ipWhiteList:
    sourceRange:
      - 10.27.20.0/24
      - 10.27.25.0/24
      - 10.27.255.0/24
      - 100.64.0.0/10
