apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuclearlaunch
  namespace: ctf
spec:
  selector:
    matchLabels:
      app: nuclearlaunch
  template:
    metadata:
      labels:
        app: nuclearlaunch
    spec:
      containers:
        - name: nuclearlaunch
          image: gitlab.oplabs.us:5050/root/ctf-web-php:latest
          pull-policy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
