apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-email-secret
    namespace: lubelogger
type: Opaque
data:
    MailConfig__EmailServer: ENC[AES256_GCM,data:W0n1G0iUETfeZUgxB55Cg08pWiOljCgtbXj8evCHXCU=,iv:Z7+/qBL/4826AolCJZ2WK7in2p9WqOIR7xj81/5j8zI=,tag:ZH3A33uhV5wnnavoA45xNQ==,type:str]
    MailConfig__EmailFrom: ENC[AES256_GCM,data:UgxBDrb9UeN0U0cbCY9gqdPr74Csn8d6u+StEg==,iv:vW01NZhw1+DRiuI/p3RwIrWbKI47fBbDXNHWZU+cqkQ=,tag:cWr7xo2VGmag7gC60zJvAQ==,type:str]
    MailConfig__Port: ENC[AES256_GCM,data:DyT7,iv:IpNsD1GcjGhczZ+xUCC2kz4a/34rvZOD+HlB4y7NIl8=,tag:AHUTEyIB0pNQFEctN6rF5w==,type:int]
    MailConfig__Username: ENC[AES256_GCM,data:azftG1CREa8U068Rfycy9dJQXjKUav+I3XdLIQ==,iv:ybm4kNPDwR3tRLDFxEZOguFqtboTHNQubFyKgYjQY3I=,tag:lO7Uor2jzxOEF4C1+U8CPQ==,type:str]
    MailConfig__Password: ENC[AES256_GCM,data:mMgIv/fdbNMiInXk9tDTSAh1LStXYqxhyOXSpk1l1TCMiPru3UqJTP8evRZUCncFteY/xVE+wQk7t6zOec3PnkU7mC4=,iv:XZIM6EjvIpEWZa0LtRWeu9MPQbT1pMDOvmMUqcVh8XQ=,tag:XdRf/bRuivJzNxUn3z5pNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTTd1anlrTDdwNDhyZC9w
            ZGUxQ0FxcjB0bVBIWnh6bklqVUNoZHQ5QUE4CmJaeS9xK0RLTXRlODBJaFFtS1Q5
            YVdUa2RzOWk5Q2VGK1pxTjFKQkdIOTQKLS0tIGxKM0xldjVuYlcvQzA3Slp4WEYy
            Rk5GaUl5bm1mWWdwOG80a2Nwd2hUT1UKRAXvkRmF3b7rkYyqVUNW7NRZnAkLL0By
            3NR20WfTVV6eLVt5hG1JapPKyA969maVBDM2eplmKEgnUjO4p/M7Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T03:16:31Z"
    mac: ENC[AES256_GCM,data:TXvu0/DsuqTtVDGjoMYtf28pHb+VBYN8LCNyXNk00M8NX31HPRyPvuDD23KFcgpY55YrakQ+0LcOHFAR6NfZuT6YEXfcXrAx09F46WwqF/kLw+lMU6zkMayd/Nk/hqj/s1l2Y6QF/HztQGxRKb5jQkEzomPZtosB4FVZBJOk/Gw=,iv:k+9VPdnf4uOE041Xv98XmTlQf4fhSx4hJLqRjuVV45Q=,tag:YQAm2qdxXpgjVTuhGsBTbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
