apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-email-secret
    namespace: lubelogger
type: Opaque
data:
    MailConfig__EmailServer: ENC[AES256_GCM,data:zcTdujkrNC0AqMhgTEfuy1TWcEji2Vrl2wzPV5l+jBg=,iv:KbFHGayZR0RwETRVJgRh1VBjSyGXZm2uxeHyQBjrVxg=,tag:fXKlKABVlL/Q4giv1422fA==,type:str]
    MailConfig__EmailFrom: ENC[AES256_GCM,data:mngVVz8Kw6CZreSAj/SPcA4b2mMKp9LwivqZhA==,iv:Mq5d86gKvRk4+si5ofYYp1cFVRKJxGirbosOQW1OC9M=,tag:0H/O2U15lR5MzASB/kdieA==,type:str]
    MailConfig__Port: ENC[AES256_GCM,data:dJ1KTQ==,iv:T4wnjZEK6yIS7vaOmo86nIoZzoDrDbAzGiq+O0XIhYI=,tag:RB+cOo8OnqK3y84S+RbqvA==,type:str]
    MailConfig__Username: ENC[AES256_GCM,data:tQuffq46dyLjl/5YUUDCdqYQKFaoAyOIfmLYoA==,iv:5iGl7hfuPW4N7m3ePCojYycs9Sdxmu3+mXRMEkiA5ss=,tag:xu+yZDQOkdVSLiX0PaX5fA==,type:str]
    MailConfig__Password: ENC[AES256_GCM,data:ZKoJa+/aHuRgFSTtjg5E5f4yrZtxYJjPBCwgAwwLvzXLCkTOPHTZDLE2d4mP5Pr9ij9cQ+FzpKwRb4Lz/BWa+tqnlDw=,iv:fMwNUeEDVOaG61IAgaqS1dAX2jhjLZ+d//4hymmwxTc=,tag:3grG7MUIUN9/ETXQ67ri2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNUpkK2dFblIxcEVERU1D
            OUkxc2M0bVczV1lSc2tSZlFEaXdOZUh2UUY4ClVxdmpxNDRlSjFuQjFFSE9YNFFt
            c1lTazV6OFhFOEFTU0hCWWV0ZXowZDAKLS0tIDYwTDA4UGpTOXBHUzFEckxOVnBM
            cnljcFdzVDFXbUV2QjVJSUhMNFJjSEEK3LBWbW4vIOM+aEktOWQj0rWVujQVlnC2
            R8LeyaIRp69aD9caXhlrkzQ645dyVP0fG8HSBTJm8yXyYmlial+bUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T03:19:22Z"
    mac: ENC[AES256_GCM,data:dIvcXzKjpHh6pM/X8HLUDNM5rylz9hb07oL9cHKZrqT7WebGtr8HbFEABDCB0X34PcZKFPK4UWaCa5on1sax1Trwu88GEwnwVmEeXCViKhwoY0OPGhsS3TJQg0cEScskC9V5Izi7iWBODeVT1/KDmUWFxvpTMbJQpiR6i6KYmIA=,iv:8H9EhQ9YoDeUxNl3BtlL+du9IFKhvENb9xqxdsTianQ=,tag:43VIm1A0vfYenARJXRF1fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
