apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-openid-secret
    namespace: lubelogger
type: Opaque
data:
    clientId: ENC[AES256_GCM,data:gjR9UaK9jg6adG9uClTMc0DBl6Ss91kzCNxNa8TJ8JPlVV18MRoBO9FjJQ+YP7VoLkf70BACLYQ=,iv:4wvP1cGtw8oksSvZC7RlXfDKrtfgtZqIzSi5oJjuENk=,tag:C5PF7JKHmD5nFZ5It9bF6w==,type:str]
    clientSecret: ENC[AES256_GCM,data:/z8JVQOgsdJl60+s4VHp32nNjJJ+UEc0oCXuaBvr2iI8LrGOnwXHgjhksRd/uVqY15xluSvVn4WmJCJ67S9MlgjwgxtSWK7glUEemu1UOpSoDnAt5Sk2j8LFwkoVu6c/tLxNPoZ7APDMyyZ9PtNul0lM3fN/7AJNdDhV4ip9yxCTNsEXKPJlcX6V1uhuy5Mbk0A5gGPK8WCsEKHwGc+5NTrEmE8UQbyd/VHiUQ==,iv:m854Qy6cfOEjDgffo4Gy6P1tsRuCdLMBtoO8up1ICks=,tag:mKQqpEyDw0kiXeHMeO539g==,type:str]
    authUrl: ENC[AES256_GCM,data:+A+zPwaywiB1cyHUmlZpU2un8jTPhG3iKunQpGE/W1oCxHXVSiXzx9V30DBWwhOjI6tmGNqenJ/WAWYUArQN5w==,iv:BlW1x7noHuuYn89hE4WnENM6bNKsCj00//QO2uU5xlY=,tag:d7dK87RJ9SxOsb6GufFeDA==,type:str]
    tokenUrl: ENC[AES256_GCM,data:6VL407HMpUiKqjxU1u7Vz/jQMH9Cf9blryCK//SxUycd0+PMH92LcPTPYwwWZwFlM8hkGl7K33LcK3eS,iv:dusUilgGhwT6dohPJQrkv6WiTD4B+372QMg3N3OCe70=,tag:1WjPKn41xURiGDxfgf794g==,type:str]
    userInfoUrl: ENC[AES256_GCM,data:u/jKL3wTiwlsVHTjnOhg/pW2dRav7bKyxKP3PaYDMUxq/flU2Udo3Dz1bzGwROg7DG6fPsTgrjWKH7sGvgKxNw==,iv:1YyxXnY/kK+ZGrLsDXxOUIg4M8Yooyy5ru3Rocn79AI=,tag:R6rUOVOEX5GfP3whEN7bHw==,type:str]
    logoutUrl: ENC[AES256_GCM,data:8MhUdgYhPR8vFZgUsIvfEhlKP0xXhcHslIax8mVvHg0oWyMVfXs0e0Fc22WEG9DUN5grjW09xyJPPWeJR8XBLOwE/Y40LwynQtt28r0CWVM=,iv:mkiFE4PaOwMRhwR5SNTu4FpH4V35TDE+JRQjMD2OMt0=,tag:IuxAUVuwjTAgAzwdIbZ53Q==,type:str]
    scope: ENC[AES256_GCM,data:KCUqpApF+jpfkmQGw3STK9oQtK1Y+oo7X+flqA==,iv:dEXeQW4olUHsPGFdYN7k2Jytotk4UODhjwTrhLsxC9c=,tag:vEOGsr5NMZJQcpg+NQuw2Q==,type:str]
    DefaultReminderEmail: ENC[AES256_GCM,data:ND5/giHaGJBHxWpFOLaR6f60+no5HPGFWBUXDw==,iv:tDtrntOFTnpMsCedjMy73kjax5FfTKTp1CS+VOUWd78=,tag:dN8ejLQy79lc2nhtkPDuxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSE9LMklqUHEvYlN1ckJz
            ZHBPN1lEOHBDTXR6NFEzUG5rdUptNis4U0UwClpGQjFBbkwxL0M0RFNnL1NtT3Fh
            K0dYNlNmNjhHOUwyeHp5VldjemxFZDQKLS0tIFNNNi8rK2gwRERoZmo4OFI4RHJV
            cUx3ZmVPMjBYN3psVU1IaGpUQ3Faa2sKdR8Bd6G1IJsAk2w+VYUwEXCdUfNgjKKp
            5/BXaD+zb33M8SAnKlfVYa2nI/chWq7Lo6iy2cmp6Sevva6XgUWEew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T01:18:50Z"
    mac: ENC[AES256_GCM,data:uPfEa/BG9XOwKnr8QDO0EBcNOhXzsJ7jdRfNYhEhG6kybPCT7cZuWtl24K3Jk1RAHueHwS7g94eyjNrK7Z5UyOzpRrn6FCwBulFgyjD6TWyuD8pjF5Dt/f+TSz9VXLGh0V60qr62jW12yn/hBKnevsUiJaHq39ASdKUnDGo7gLY=,iv:ESn6PiI0qjYkgB/2Nkda3Xp0oM4frQQbT4bRm9tH+JU=,tag:jYBTWIxzzpUJez4tvrKnsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
