apiVersion: v1
kind: Secret
metadata:
    name: lubelogger-config-secret
    namespace: lubelogger
type: Opaque
stringData:
    appsettings.json: ENC[AES256_GCM,data:JmIZnuKyo0lyZArcFU/AIN6QpPwDRrH1/s05uuCYlN9dogZkP/N8haU7kIzOsEJwGzgSLhp1lFbZjaRYb32/BWC5QaYVoNz5Kw/d+hjlxVfkRmQVuhFtwAXtLctc9UKaMi7dVOu/Vlw=,iv:fSLFjYwWEaG5npdGOs6+GkSR9/26jBXHhe4J+P4wEh4=,tag:gdRPPHvaGVnOXqiUJlCdPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jnxnx6ppeusvyhuqqk2n8ak2ntvj8pkc223yjfve500au0jyp42q9ckf20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U05iY1l4di9lV09KQ3B6
            SE9ya0xhaTBUTlhLRWFjN3g2eDNiVStsalRjClgzeThPZmpiUHRsMElKYXA5NGFi
            YWtOYUtZbVdxbEhNcWhPUkxaNS91TWsKLS0tIE0xd3N3em44YW5RMHhnT1ROd3ZO
            d0ZOVnlZTGdaUnVvYVpTdnVzQ1R0aGcKUrQ10d//znFpt+/yT/nWpl8TX4ocQbiX
            KfErZ2iCglXydBQHhd5xese/5SUVaKBn0w0Nmc3pIiGJ7DvP8l7xBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-03T03:36:26Z"
    mac: ENC[AES256_GCM,data:5ruK5dlzkgO9wdt+R76KnEZ/63//Y1/Ng+HuILO0iNsyU1GC0qgZRczV2tzz2dqd/3EoR3Wemydllvk1Gq/MHBi0FvN+1NHVrcslfTnQ1xh5FCfbdlwD/cyhrZBmukUCJrgg4tU3HN6iPqXNpW5qjcQmzqBdTnSweTSLWjPP3+w=,iv:qyV84kgPiAarozXdtjjSMng1xgcaJHZW24qh7OXqceM=,tag:vjKHytPypYN865II4MCtoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|annotations|values|)$
    version: 3.8.1
